// Compact general-knowledge bank: [question, A, B, C, D, correctIndex]
window.QUIZ_RAW = [
  ["What is the chemical symbol for gold?", "Au", "Ag", "Fe", "Pb", 0],
  ["Which planet is known as the Red Planet?", "Venus", "Mars", "Jupiter", "Mercury", 1],
  ["What is the largest ocean on Earth?", "Atlantic", "Indian", "Arctic", "Pacific", 3],
  ["How many continents are there?", "5", "6", "7", "8", 2],
  ["What gas do plants absorb from the air?", "Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen", 2],
  ["Which country has the most people?", "India", "United States", "Indonesia", "Brazil", 0],
  ["What is H2O more commonly known as?", "Salt", "Water", "Air", "Sugar", 1],
  ["Which animal is known as the king of the jungle?", "Tiger", "Elephant", "Lion", "Gorilla", 2],
  ["How many sides does a hexagon have?", "5", "6", "7", "8", 1],
  ["What is the capital of Japan?", "Seoul", "Beijing", "Tokyo", "Osaka", 2],
  ["Which instrument measures temperature?", "Barometer", "Thermometer", "Hygrometer", "Altimeter", 1],
  ["What is the fastest land animal?", "Lion", "Horse", "Cheetah", "Greyhound", 2],
  ["Which year did World War II end?", "1943", "1944", "1945", "1946", 2],
  ["What do bees collect to make honey?", "Pollen", "Nectar", "Sap", "Dew", 1],
  ["How many degrees are in a right angle?", "45", "90", "180", "360", 1],
  ["Which organ pumps blood through the body?", "Lungs", "Liver", "Heart", "Kidney", 2],
  ["What is the tallest mountain above sea level?", "K2", "Mount Everest", "Kilimanjaro", "Denali", 1],
  ["Which color do you get by mixing blue and yellow?", "Purple", "Orange", "Green", "Brown", 2],
  ["What is the boiling point of water at sea level?", "90°C", "95°C", "100°C", "110°C", 2],
  ["Which desert is the largest hot desert?", "Gobi", "Sahara", "Kalahari", "Mojave", 1],
  ["How many bones are in an adult human body?", "186", "206", "226", "256", 1],
  ["What is the capital of France?", "Lyon", "Marseille", "Paris", "Nice", 2],
  ["Which force keeps us on the ground?", "Magnetism", "Friction", "Gravity", "Inertia", 2],
  ["What is the smallest prime number?", "0", "1", "2", "3", 2],
  ["What is the largest mammal?", "Elephant", "Blue whale", "Giraffe", "Hippopotamus", 1],
  ["How many planets are in our solar system?", "7", "8", "9", "10", 1],
  ["What is the capital of Australia?", "Sydney", "Melbourne", "Canberra", "Perth", 2],
  ["Which metal is liquid at room temperature?", "Iron", "Mercury", "Copper", "Zinc", 1],
  ["What do you call a baby cat?", "Cub", "Pup", "Kitten", "Calf", 2],
  ["How many hours are in a day?", "12", "24", "36", "48", 1],
  ["Which continent is Egypt in?", "Asia", "Europe", "Africa", "South America", 2],
  ["What is the square root of 64?", "6", "7", "8", "9", 2],
  ["Which blood cells help fight infection?", "Red", "White", "Platelets", "Plasma", 1],
  ["What is the currency of the United Kingdom?", "Euro", "Dollar", "Pound", "Franc", 2],
  ["Which gas makes up most of Earth's atmosphere?", "Oxygen", "Carbon dioxide", "Nitrogen", "Helium", 2],
  ["What is the longest river in the world by most measures?", "Amazon", "Nile", "Yangtze", "Mississippi", 1],
  ["How many legs does a spider have?", "6", "8", "10", "12", 1],
  ["Which planet is closest to the Sun?", "Venus", "Earth", "Mercury", "Mars", 2],
  ["What is the capital of Italy?", "Milan", "Venice", "Rome", "Naples", 2],
  ["Which vitamin do you mainly get from sunlight?", "Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D", 3],
  ["What is 15% of 200?", "20", "25", "30", "35", 2],
  ["Which ocean contains the Bermuda Triangle?", "Pacific", "Atlantic", "Indian", "Arctic", 1],
  ["What is the hardest natural substance?", "Gold", "Iron", "Diamond", "Quartz", 2],
  ["Which country is most associated with inventing pizza?", "France", "Greece", "Italy", "Spain", 2],
  ["How many players are on a soccer team on the field?", "9", "10", "11", "12", 2],
  ["What is the capital of Canada?", "Toronto", "Vancouver", "Ottawa", "Montreal", 2],
  ["Which animal lays the largest eggs?", "Chicken", "Ostrich", "Emu", "Penguin", 1],
  ["What does DNA stand for?", "Digital Network Array", "Deoxyribonucleic acid", "Dynamic Nuclear Atom", "Double Nitrogen Acid", 1],
  ["Which season comes after winter?", "Summer", "Autumn", "Spring", "Monsoon", 2],
  ["What is the freezing point of water in Celsius?", "0°C", "10°C", "32°C", "-10°C", 0],
  ["Which country is shaped like a boot?", "Portugal", "Italy", "Greece", "Chile", 1],
  ["How many teeth does an adult human usually have?", "28", "30", "32", "34", 2],
  ["What is the capital of Spain?", "Barcelona", "Madrid", "Seville", "Valencia", 1],
  ["Which sense is related to the olfactory system?", "Sight", "Hearing", "Smell", "Taste", 2],
  ["What is the largest planet in our solar system?", "Saturn", "Neptune", "Jupiter", "Uranus", 2],
  ["Which language has the most native speakers?", "English", "Spanish", "Mandarin Chinese", "Hindi", 2],
  ["What is the main ingredient in guacamole?", "Tomato", "Avocado", "Pepper", "Onion", 1],
  ["How many days are in a leap year?", "364", "365", "366", "367", 2],
  ["Which bird is a common symbol of peace?", "Eagle", "Dove", "Swan", "Owl", 1],
  ["What is the capital of Germany?", "Munich", "Hamburg", "Berlin", "Frankfurt", 2],
  ["Which element has the symbol O?", "Gold", "Oxygen", "Osmium", "Oxide", 1],
  ["What shape has 4 equal sides and 4 right angles?", "Rectangle", "Rhombus", "Square", "Trapezoid", 2],
  ["Which country is home to the kangaroo?", "New Zealand", "Australia", "South Africa", "India", 1],
  ["What is the speed of light roughly?", "300,000 km/s", "30,000 km/s", "3,000 km/s", "300 km/s", 0],
  ["Which part of the plant conducts photosynthesis?", "Roots", "Stem", "Leaves", "Flowers", 2],
  ["What is the capital of Brazil?", "Rio de Janeiro", "São Paulo", "Brasília", "Salvador", 2],
  ["How many strings does a standard guitar have?", "4", "5", "6", "7", 2],
  ["Which scientist developed the theory of relativity?", "Newton", "Einstein", "Galileo", "Tesla", 1],
  ["What is the largest internal organ in humans?", "Heart", "Brain", "Liver", "Stomach", 2],
  ["Which sea is the saltiest?", "Black Sea", "Red Sea", "Dead Sea", "Caspian Sea", 2],
  ["What is 9 × 8?", "64", "72", "81", "88", 1],
  ["Which country built the Great Wall?", "Japan", "China", "Korea", "Mongolia", 1],
  ["What do you call water in solid form?", "Steam", "Ice", "Vapor", "Mist", 1],
  ["Which planet has famous rings?", "Mars", "Jupiter", "Saturn", "Venus", 2],
  ["What is the capital of Egypt?", "Alexandria", "Giza", "Cairo", "Luxor", 2],
  ["Which animal is a marsupial?", "Rabbit", "Kangaroo", "Deer", "Bear", 1],
  ["What is the chemical symbol for iron?", "Ir", "In", "Fe", "I", 2],
  ["Which instrument has 88 keys?", "Organ", "Piano", "Harpsichord", "Accordion", 1],
  ["What is the capital of India?", "Mumbai", "New Delhi", "Kolkata", "Chennai", 1],
  ["How many weeks are in a year?", "48", "50", "52", "54", 2],
  ["Which fruit is typically yellow and curved?", "Mango", "Banana", "Papaya", "Lemon", 1],
  ["What is the study of stars and planets called?", "Geology", "Biology", "Astronomy", "Chemistry", 2],
  ["Which country is famous for tulips and windmills?", "Belgium", "Netherlands", "Denmark", "Sweden", 1],
  ["What is the opposite of east?", "North", "South", "West", "Northeast", 2],
  ["How many milliliters are in a liter?", "10", "100", "1000", "10000", 2],
  ["Which animal can change color to camouflage?", "Frog", "Chameleon", "Snake", "Lizard", 1],
  ["What is the capital of Russia?", "St. Petersburg", "Moscow", "Kazan", "Sochi", 1],
  ["Which layer of Earth do we live on?", "Mantle", "Core", "Crust", "Outer core", 2],
  ["What is pi approximately equal to?", "2.14", "3.14", "4.14", "1.41", 1],
  ["Which sport uses a shuttlecock?", "Tennis", "Badminton", "Squash", "Ping pong", 1],
  ["What is the largest country by land area?", "Canada", "China", "United States", "Russia", 3],
  ["How many chambers does the human heart have?", "2", "3", "4", "5", 2],
  ["Which planet is known for its Great Red Spot?", "Mars", "Jupiter", "Saturn", "Neptune", 1],
  ["What is the capital of South Korea?", "Busan", "Incheon", "Seoul", "Daegu", 2],
  ["Which tree produces acorns?", "Pine", "Oak", "Maple", "Birch", 1],
  ["What is 2 to the power of 5?", "16", "25", "32", "64", 2],
  ["Which ocean lies between Africa and Australia?", "Atlantic", "Pacific", "Indian", "Arctic", 2],
  ["What is the main language of Brazil?", "Spanish", "Portuguese", "French", "English", 1],
  ["Which insect produces silk?", "Bee", "Ant", "Silkworm", "Butterfly", 2],
  ["What is the chemical symbol for silver?", "Si", "Sv", "Ag", "Sr", 2],
  ["Which mountain range contains Mount Everest?", "Andes", "Alps", "Himalayas", "Rockies", 2],
  ["How many zeros are in one million?", "4", "5", "6", "7", 2],
  ["What is the capital of Mexico?", "Guadalajara", "Cancún", "Mexico City", "Monterrey", 2],
  ["Which animal is the tallest?", "Elephant", "Giraffe", "Moose", "Camel", 1],
  ["What do we call animals that eat only plants?", "Carnivores", "Omnivores", "Herbivores", "Insectivores", 2],
  ["Which unit measures electric current?", "Volt", "Watt", "Ampere", "Ohm", 2],
  ["What is the largest island in the world?", "Madagascar", "Greenland", "Borneo", "Great Britain", 1],
  ["How many colors are in a rainbow?", "5", "6", "7", "8", 2],
  ["Which country gifted the Statue of Liberty to the US?", "England", "Spain", "France", "Italy", 2],
  ["What is the capital of Sweden?", "Oslo", "Copenhagen", "Stockholm", "Helsinki", 2],
  ["What is the process of water turning into vapor?", "Condensation", "Evaporation", "Freezing", "Melting", 1],
  ["How many sides does an octagon have?", "6", "7", "8", "9", 2],
  ["Which vitamin is abundant in oranges?", "Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin K", 2],
  ["What is the capital of Turkey?", "Istanbul", "Ankara", "Izmir", "Antalya", 1],
  ["Which bird cannot fly?", "Eagle", "Penguin", "Sparrow", "Hawk", 1],
  ["What is the chemical formula for table salt?", "H2O", "CO2", "NaCl", "CaCO3", 2],
  ["How many minutes are in 3 hours?", "120", "150", "180", "210", 2],
  ["What is the capital of Argentina?", "Santiago", "Lima", "Buenos Aires", "Montevideo", 2],
  ["Which part of the eye controls how much light enters?", "Retina", "Iris", "Lens", "Cornea", 1],
  ["What is 100 divided by 4?", "20", "25", "30", "40", 1],
  ["Which country is both a continent and a country?", "Greenland", "Australia", "Iceland", "Madagascar", 1],
  ["What do pandas mainly eat?", "Fish", "Bamboo", "Insects", "Fruit", 1],
  ["Which gas do humans need to breathe?", "Nitrogen", "Carbon dioxide", "Oxygen", "Helium", 2],
  ["What is the capital of Norway?", "Bergen", "Oslo", "Trondheim", "Stavanger", 1],
  ["How many faces does a cube have?", "4", "6", "8", "12", 1],
  ["Which scientist discovered penicillin?", "Pasteur", "Fleming", "Curie", "Darwin", 1],
  ["What is the largest bone in the human body?", "Skull", "Femur", "Tibia", "Humerus", 1],
  ["Which sea separates Europe and Africa?", "Black Sea", "Red Sea", "Mediterranean Sea", "Baltic Sea", 2],
  ["What is the capital of Poland?", "Kraków", "Warsaw", "Gdańsk", "Wrocław", 1],
  ["Which number is a perfect square?", "12", "15", "16", "18", 2],
  ["What is the study of living things called?", "Physics", "Chemistry", "Biology", "Geology", 2],
  ["Which animal is known for its black and white stripes?", "Tiger", "Zebra", "Panda", "Skunk", 1],
  ["What is the capital of Greece?", "Thessaloniki", "Athens", "Patras", "Heraklion", 1],
  ["How many millimeters are in a centimeter?", "5", "10", "100", "1000", 1],
  ["Which planet is farthest from the Sun?", "Uranus", "Neptune", "Pluto", "Saturn", 1],
  ["What is the main gas in soda bubbles?", "Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen", 2],
  ["Which country has the city of Dubai?", "Saudi Arabia", "Qatar", "United Arab Emirates", "Oman", 2],
  ["What do you call a group of wolves?", "Herd", "Pack", "Flock", "School", 1],
  ["Which element is diamond made of?", "Silicon", "Carbon", "Calcium", "Iron", 1],
  ["What is the capital of Portugal?", "Porto", "Lisbon", "Braga", "Coimbra", 1],
  ["How many seconds are in a minute?", "30", "60", "90", "100", 1],
  ["Which continent has the most countries?", "Asia", "Europe", "Africa", "South America", 2],
  ["What is the lightest element?", "Helium", "Hydrogen", "Oxygen", "Lithium", 1],
  ["Which animal sleeps while hanging upside down?", "Owl", "Bat", "Sloth", "Koala", 1],
  ["What is the capital of Thailand?", "Phuket", "Chiang Mai", "Bangkok", "Pattaya", 2],
  ["How many degrees are in a full circle?", "90", "180", "270", "360", 3],
  ["What invention is Thomas Edison famous for popularizing?", "Telephone", "Practical light bulb", "Airplane", "Radio", 1],
  ["What is the largest rainforest?", "Congo", "Amazon", "Daintree", "Borneo", 1],
  ["Which country uses the yen?", "China", "South Korea", "Japan", "Taiwan", 2],
  ["What is the capital of Denmark?", "Aarhus", "Odense", "Copenhagen", "Aalborg", 2],
  ["How many pairs of ribs does a human usually have?", "10", "12", "14", "16", 1],
  ["Which sport is played at Wimbledon?", "Golf", "Tennis", "Cricket", "Rugby", 1],
  ["What is the chemical symbol for sodium?", "So", "Sd", "Na", "S", 2],
  ["Which bird is among the fastest flyers?", "Eagle", "Peregrine falcon", "Swallow", "Hawk", 1],
  ["What is the capital of Ireland?", "Cork", "Galway", "Dublin", "Limerick", 2],
  ["How many bits are in a byte?", "4", "8", "16", "32", 1],
  ["Which ocean is the coldest?", "Atlantic", "Pacific", "Indian", "Arctic", 3],
  ["What do caterpillars turn into?", "Beetles", "Butterflies or moths", "Flies", "Bees", 1],
  ["Which country is famous for the Eiffel Tower?", "Italy", "Spain", "France", "Belgium", 2],
  ["What is the capital of Finland?", "Tampere", "Turku", "Helsinki", "Oulu", 2],
  ["How many months have 31 days?", "5", "6", "7", "8", 2],
  ["Which organ helps you breathe?", "Liver", "Lungs", "Kidney", "Pancreas", 1],
  ["Which planet is tilted on its side?", "Neptune", "Uranus", "Saturn", "Venus", 1],
  ["What is the capital of Belgium?", "Antwerp", "Ghent", "Brussels", "Bruges", 2],
  ["How many Olympic rings are there?", "4", "5", "6", "7", 1],
  ["Which natural disaster is measured with the Richter scale?", "Tornado", "Earthquake", "Hurricane", "Flood", 1],
  ["What is the capital of New Zealand?", "Auckland", "Christchurch", "Wellington", "Hamilton", 2],
  ["How many sides does a triangle have?", "2", "3", "4", "5", 1],
  ["Which animal is often called man's best friend?", "Cat", "Dog", "Horse", "Rabbit", 1],
  ["What is the main currency of the European Union?", "Pound", "Franc", "Euro", "Mark", 2],
  ["What stores data permanently on a computer?", "RAM", "CPU", "Hard drive / SSD", "GPU", 2],
  ["What is the capital of Iceland?", "Akureyri", "Reykjavík", "Keflavík", "Húsavík", 1],
  ["How many legs does an insect usually have?", "4", "6", "8", "10", 1],
  ["Which wall once divided Berlin?", "Great Wall", "Hadrian's Wall", "Berlin Wall", "Western Wall", 2],
  ["What is dry ice made of?", "Frozen water", "Frozen carbon dioxide", "Frozen nitrogen", "Frozen oxygen", 1],
  ["What is the capital of Hungary?", "Debrecen", "Budapest", "Szeged", "Pécs", 1],
  ["How many cards are in a standard deck without jokers?", "48", "50", "52", "54", 2],
  ["Which sense uses the cochlea?", "Sight", "Smell", "Hearing", "Touch", 2],
  ["What is the largest volcano on Earth (shield)?", "Etna", "Mauna Loa", "Vesuvius", "Fuji", 1],
  ["Which country is Prague the capital of?", "Poland", "Austria", "Czechia", "Slovakia", 2],
  ["How many zeros are in one billion?", "6", "7", "8", "9", 3],
  ["Which animal produces wool?", "Goat", "Sheep", "Cow", "Pig", 1],
  ["What is the capital of Austria?", "Salzburg", "Vienna", "Innsbruck", "Graz", 1],
  ["Which planet is densest?", "Jupiter", "Saturn", "Earth", "Neptune", 2],
  ["What is a young frog called?", "Pup", "Cub", "Tadpole", "Fry", 2],
  ["Which country invented paper?", "Egypt", "China", "Greece", "India", 1],
  ["What is the capital of Chile?", "Valparaíso", "Santiago", "Concepción", "Antofagasta", 1],
  ["How many primary colors are there in traditional painting?", "2", "3", "4", "5", 1],
  ["Which organ filters blood in the human body?", "Heart", "Liver", "Kidneys", "Stomach", 2],
  ["What is the capital of Saudi Arabia?", "Jeddah", "Mecca", "Riyadh", "Medina", 2],
  ["Which fish is known for migrating upstream to spawn?", "Tuna", "Salmon", "Cod", "Shark", 1],
  ["What does Wi-Fi allow devices to do?", "Print only", "Connect wirelessly to a network", "Charge batteries", "Cool down", 1],
  ["Which country has the city of Marrakech?", "Algeria", "Tunisia", "Morocco", "Egypt", 2],
  ["How many innings are in a standard baseball game?", "7", "8", "9", "10", 2],
  ["What is the capital of Ukraine?", "Kharkiv", "Odesa", "Kyiv", "Lviv", 2],
  ["Which element is needed for strong bones?", "Iron", "Calcium", "Sodium", "Zinc", 1],
  ["What is the largest moon of Saturn?", "Europa", "Ganymede", "Titan", "Io", 2],
  ["Which country is home to Machu Picchu?", "Chile", "Bolivia", "Peru", "Ecuador", 2],
  ["What is the capital of Vietnam?", "Ho Chi Minh City", "Hanoi", "Da Nang", "Hue", 1],
  ["Which animal has a pouch?", "Rabbit", "Koala", "Deer", "Fox", 1],
  ["What is the chemical symbol for helium?", "H", "He", "Hl", "Hm", 1],
  ["Which desert is among the driest on Earth?", "Sahara", "Gobi", "Atacama", "Kalahari", 2],
  ["What is the capital of Colombia?", "Medellín", "Cali", "Bogotá", "Cartagena", 2],
  ["How many Great Lakes are there in North America?", "3", "4", "5", "6", 2],
  ["Which scientist proposed natural selection?", "Newton", "Darwin", "Mendel", "Hawking", 1],
  ["What is the capital of Malaysia?", "Johor Bahru", "Penang", "Kuala Lumpur", "Malacca", 2],
  ["Which tool measures earthquakes?", "Thermometer", "Seismograph", "Barometer", "Anemometer", 1],
  ["What is 12 squared?", "124", "144", "164", "132", 1],
  ["Which country has the city of Casablanca?", "Tunisia", "Morocco", "Algeria", "Libya", 1],
  ["How many wings does a bee have?", "2", "4", "6", "8", 1],
  ["What is the capital of the Philippines?", "Cebu", "Davao", "Manila", "Quezon City", 2],
  ["Which planet is often called the Morning Star?", "Mars", "Venus", "Mercury", "Jupiter", 1],
  ["Which country is famous for maple syrup?", "USA", "Canada", "Norway", "Sweden", 1],
  ["What is the capital of Romania?", "Cluj", "Timișoara", "Bucharest", "Iași", 2],
  ["How many letters are in the English alphabet?", "24", "25", "26", "27", 2],
  ["Which animal has black and white fur and eats bamboo?", "Zebra", "Penguin", "Panda", "Skunk", 2],
  ["What is the capital of Kenya?", "Mombasa", "Nairobi", "Kisumu", "Nakuru", 1],
  ["Which unit measures mass?", "Meter", "Liter", "Kilogram", "Second", 2],
  ["What is the largest coral reef system?", "Red Sea Reef", "Great Barrier Reef", "Belize Barrier Reef", "New Caledonia Reef", 1],
  ["How many players are on a basketball court per team?", "4", "5", "6", "7", 1],
  ["What is the capital of Croatia?", "Split", "Zagreb", "Dubrovnik", "Rijeka", 1],
  ["Which gas is used in party balloons that float?", "Oxygen", "Nitrogen", "Helium", "Carbon dioxide", 2],
  ["What is the smallest country in the world?", "Monaco", "Vatican City", "San Marino", "Liechtenstein", 1],
  ["Which animal is a reptile?", "Frog", "Snake", "Newt", "Salamander", 1],
  ["What is the capital of Peru?", "Cusco", "Arequipa", "Lima", "Trujillo", 2],
  ["How many centimeters are in a meter?", "10", "100", "1000", "10000", 1],
  ["Which famous tower leans in Italy?", "Eiffel Tower", "Tower of London", "Leaning Tower of Pisa", "CN Tower", 2],
  ["Which sense detects sweetness?", "Smell", "Taste", "Touch", "Hearing", 1],
  ["Which country is famous for fjords?", "Sweden", "Norway", "Finland", "Denmark", 1],
  ["How many sides does a pentagon have?", "4", "5", "6", "7", 1],
  ["What is the capital of Indonesia?", "Surabaya", "Bandung", "Jakarta", "Denpasar", 2],
  ["Which animal is the largest land mammal?", "Rhino", "Hippo", "African elephant", "Giraffe", 2],
  ["What does a compass primarily show?", "Temperature", "Direction", "Altitude", "Speed", 1],
  ["How many moons does Earth have?", "0", "1", "2", "3", 1],
  ["What is the capital of Nigeria?", "Lagos", "Kano", "Abuja", "Ibadan", 2],
  ["Which fruit has seeds on the outside?", "Raspberry", "Strawberry", "Blueberry", "Grape", 1],
  ["What is the boiling point of water in Fahrenheit?", "100°F", "180°F", "212°F", "232°F", 2],
  ["How many quarters make one whole?", "2", "3", "4", "5", 2],
  ["What is the capital of Scotland?", "Glasgow", "Aberdeen", "Edinburgh", "Dundee", 2],
  ["Which planet has a day longer than its year?", "Mars", "Venus", "Mercury", "Jupiter", 1],
  ["What is the main ingredient in bread?", "Rice", "Flour", "Corn", "Potato", 1],
  ["Which ocean is east of the Americas?", "Pacific", "Atlantic", "Indian", "Southern", 1],
  ["How many zeros are in ten thousand?", "3", "4", "5", "6", 1],
  ["What is the capital of Switzerland?", "Zurich", "Geneva", "Bern", "Basel", 2],
  ["Which animal can live both on land and in water?", "Bird", "Amphibian", "Fish", "Insect", 1],
  ["What is the chemical symbol for carbon?", "Ca", "Co", "C", "Cr", 2],
  ["How many days does February have in a common year?", "27", "28", "29", "30", 1],
  ["What is the capital of Pakistan?", "Karachi", "Lahore", "Islamabad", "Peshawar", 2],
  ["Which bird is known for mimicking sounds?", "Crow", "Parrot", "Sparrow", "Pigeon", 1],
  ["What is 7 × 7?", "42", "47", "49", "56", 2],
  ["Which mountain is the highest in Africa?", "Mount Kenya", "Kilimanjaro", "Atlas", "Drakensberg", 1],
  ["How many oceans are commonly counted on Earth?", "3", "4", "5", "6", 2],
  ["Which tool is used to see tiny objects?", "Telescope", "Microscope", "Periscope", "Binoculars", 1],
  ["What is the capital of Iran?", "Isfahan", "Shiraz", "Tehran", "Tabriz", 2],
  ["What does HTML stand for?", "HyperText Markup Language", "High Tech Modern Language", "Home Tool Markup Link", "Hyper Transfer Mail Language", 0],
  ["How many years are in a decade?", "5", "10", "20", "100", 1],
  ["What is water called when it is a gas?", "Ice", "Steam / vapor", "Frost", "Hail", 1],
  ["What is 50% of 90?", "35", "40", "45", "50", 2],
  ["Which famous desert is in China and Mongolia?", "Sahara", "Gobi", "Kalahari", "Thar", 1],
  ["What is the capital of Serbia?", "Novi Sad", "Belgrade", "Niš", "Kragujevac", 1],
  ["What is the capital of Ethiopia?", "Dire Dawa", "Addis Ababa", "Mekelle", "Gondar", 1],
  ["Which sport uses a puck?", "Lacrosse", "Hockey", "Polo", "Tennis", 1],
  ["What is 3 cubed?", "6", "9", "27", "81", 2],
  ["What is the capital of Jordan?", "Aqaba", "Amman", "Irbid", "Zarqa", 1],
  ["How many strings does a violin have?", "3", "4", "5", "6", 1],
  ["Which country invented the compass?", "Greece", "China", "Egypt", "India", 1],
  ["What is the capital of Morocco?", "Casablanca", "Marrakech", "Rabat", "Fes", 2],
  ["Which planet is the hottest?", "Mercury", "Venus", "Mars", "Jupiter", 1],
  ["What do you call a scientist who studies rocks?", "Biologist", "Geologist", "Chemist", "Astronomer", 1],
  ["How many centimeters are in an inch (approx.)?", "1.5", "2.54", "3.5", "5", 1],
  ["What is the capital of Lebanon?", "Tripoli", "Beirut", "Sidon", "Byblos", 1],
  ["Which animal is the symbol of the WWF?", "Tiger", "Panda", "Elephant", "Whale", 1],
  ["What is 1 kilometer in meters?", "10", "100", "1000", "10000", 2],
  ["How many wheels does a unicycle have?", "0", "1", "2", "3", 1],
  ["Which part of a plant absorbs water from soil?", "Leaves", "Flowers", "Roots", "Fruit", 2],
  ["What is the chemical symbol for potassium?", "P", "Po", "K", "Pt", 2],
  ["How many players are on a volleyball court per team?", "4", "5", "6", "7", 2],
  ["Which mammal can truly fly?", "Flying squirrel", "Bat", "Ostrich", "Penguin", 1],
  ["What is 8 × 9?", "63", "72", "81", "89", 1],
  ["Which ocean surrounds Antarctica?", "Atlantic", "Pacific", "Southern Ocean", "Indian", 2],
  ["What is the capital of Ecuador?", "Guayaquil", "Quito", "Cuenca", "Manta", 1],
  ["How many halves make a whole?", "1", "2", "3", "4", 1],
  ["What is the main language of Argentina?", "Portuguese", "Spanish", "Italian", "French", 1],
  ["What is the capital of Afghanistan?", "Kandahar", "Herat", "Kabul", "Mazar-i-Sharif", 2],
  ["How many months have exactly 30 days?", "3", "4", "5", "6", 1],
  ["Which invention is Alexander Graham Bell known for?", "Light bulb", "Telephone", "Radio", "Television", 1],
  ["What is the capital of Uruguay?", "Salto", "Montevideo", "Punta del Este", "Paysandú", 1],
  ["Which star is at the center of our solar system?", "Polaris", "The Sun", "Sirius", "Alpha Centauri", 1],
  ["What is 20% of 50?", "5", "10", "15", "20", 1],
  ["Which animal is known for its long neck?", "Camel", "Giraffe", "Llama", "Ostrich", 1],
  ["What is the capital of Tunisia?", "Sfax", "Tunis", "Sousse", "Bizerte", 1],
  ["How many days are in September?", "28", "29", "30", "31", 2],
  ["Which common metal is magnetic?", "Copper", "Aluminum", "Iron", "Gold", 2],
  ["What is the capital of Cambodia?", "Siem Reap", "Phnom Penh", "Battambang", "Sihanoukville", 1],
  ["How many zeros are in one hundred?", "1", "2", "3", "4", 1],
  ["What is the capital of Slovenia?", "Maribor", "Ljubljana", "Celje", "Koper", 1],
  ["Which liquid metal was once used in thermometers?", "Gallium", "Mercury", "Lead", "Tin", 1],
  ["What do plants release during photosynthesis?", "Carbon dioxide", "Oxygen", "Nitrogen", "Methane", 1],
  ["What is 11 × 11?", "111", "121", "131", "141", 1],
  ["Which sea is north of Turkey?", "Red Sea", "Black Sea", "Dead Sea", "Caspian Sea", 1],
  ["What is the capital of Slovakia?", "Košice", "Bratislava", "Prešov", "Nitra", 1],
  ["How many years are in a century?", "10", "50", "100", "1000", 2],
  ["Which planet looks blue due to methane?", "Mars", "Venus", "Neptune", "Mercury", 2],
  ["What is 0 multiplied by any number?", "1", "That number", "0", "Infinity", 2],
  ["Which animal is the largest ape?", "Chimpanzee", "Orangutan", "Gorilla", "Gibbon", 2],
  ["What is the capital of Algeria?", "Oran", "Constantine", "Algiers", "Annaba", 2],
  ["Which atmospheric layer do we live in?", "Stratosphere", "Troposphere", "Mesosphere", "Thermosphere", 1],
  ["Which fruit is typically used to make ketchup?", "Apple", "Tomato", "Cherry", "Pepper", 1],
  ["How many sides does a stop sign have?", "6", "7", "8", "9", 2],
  ["Which animal uses echolocation?", "Dog", "Bat", "Cat", "Horse", 1],
  ["What is 6 factorial (6!)?", "120", "620", "720", "820", 2],
  ["How many minutes are in half an hour?", "15", "20", "30", "45", 2],
  ["What is the capital of Estonia?", "Tartu", "Tallinn", "Narva", "Pärnu", 1],
  ["Which planet has the shortest day?", "Earth", "Jupiter", "Mars", "Venus", 1],
  ["What do you call baby dogs?", "Kittens", "Puppies", "Cubs", "Calves", 1],
  ["What is the capital of Latvia?", "Daugavpils", "Riga", "Liepāja", "Jelgava", 1],
  ["Which organ produces insulin?", "Liver", "Pancreas", "Kidney", "Spleen", 1],
  ["What is the capital of Lithuania?", "Kaunas", "Vilnius", "Klaipėda", "Šiauliai", 1],
  ["What is 9 squared?", "18", "72", "81", "99", 2],
  ["What is the capital of Belarus?", "Gomel", "Minsk", "Brest", "Vitebsk", 1],
  ["How many days are in a fortnight?", "7", "10", "14", "21", 2],
  ["Which gas do many fire extinguishers use?", "Oxygen", "Carbon dioxide", "Hydrogen", "Helium", 1],
  ["What is the capital of Georgia (the country)?", "Batumi", "Kutaisi", "Tbilisi", "Rustavi", 2],
  ["Which instrument measures wind speed?", "Barometer", "Anemometer", "Hygrometer", "Thermometer", 1],
  ["How many sides does a nonagon have?", "7", "8", "9", "10", 2],
  ["What is the capital of Armenia?", "Gyumri", "Yerevan", "Vanadzor", "Hrazdan", 1],
  ["Which ocean is west of the Americas?", "Atlantic", "Pacific", "Indian", "Arctic", 1],
  ["What is 4 cubed?", "12", "16", "64", "256", 2],
  ["What is the capital of Azerbaijan?", "Ganja", "Baku", "Sumqayit", "Lankaran", 1],
  ["What is the chemical symbol for nitrogen?", "Ni", "N", "Ng", "Na", 1],
  ["How many hours are in a week?", "148", "158", "168", "178", 2],
  ["What is the capital of Kazakhstan?", "Almaty", "Astana", "Shymkent", "Karaganda", 1],
  ["Which bird cannot fly and is from Australia?", "Penguin", "Emu", "Kiwi", "Ostrich", 1],
  ["What is 25% of 80?", "15", "20", "25", "30", 1],
  ["What is the capital of Uzbekistan?", "Samarkand", "Tashkent", "Bukhara", "Namangan", 1],
  ["Which planet is named after the Roman god of war?", "Venus", "Mars", "Jupiter", "Mercury", 1],
  ["What is the capital of Mongolia?", "Erdenet", "Ulaanbaatar", "Darkhan", "Choibalsan", 1],
  ["What is 15 × 4?", "45", "50", "60", "75", 2],
  ["How many faces does a tetrahedron have?", "3", "4", "5", "6", 1],
  ["What is the capital of Senegal?", "Thiès", "Dakar", "Saint-Louis", "Touba", 1],
  ["Which animal is a feline?", "Wolf", "Lion", "Bear", "Deer", 1],
  ["What is a main greenhouse gas from cars?", "Oxygen", "Carbon dioxide", "Nitrogen", "Argon", 1],
  ["How many days are in November?", "28", "29", "30", "31", 2],
  ["What is the capital of Tanzania?", "Dar es Salaam", "Dodoma", "Arusha", "Mwanza", 1],
  ["Which metal is used most often for electrical wires?", "Iron", "Copper", "Silver", "Lead", 1],
  ["What is the capital of Sudan?", "Port Sudan", "Khartoum", "Omdurman", "Kassala", 1],
  ["How many sides does a decagon have?", "8", "9", "10", "12", 2],
  ["What is 10 to the power of 3?", "30", "100", "1000", "10000", 2],
  ["What is the capital of Angola?", "Lobito", "Luanda", "Huambo", "Benguela", 1],
  ["How many feet are in a yard?", "2", "3", "4", "5", 1],
  ["What is the capital of Paraguay?", "Ciudad del Este", "Asunción", "Encarnación", "Luque", 1],
  ["Which planet is the smallest?", "Mars", "Venus", "Mercury", "Earth", 2],
  ["What do you call baby cows?", "Foals", "Calves", "Kids", "Lambs", 1],
  ["How many seconds are in an hour?", "600", "1800", "3600", "7200", 2],
  ["Which organ is primarily used for thinking?", "Heart", "Brain", "Liver", "Stomach", 1],
  ["What is 18 divided by 3?", "5", "6", "7", "9", 1],
  ["What is the capital of Zimbabwe?", "Bulawayo", "Harare", "Mutare", "Gweru", 1],
  ["Which animal is known for laughing sounds?", "Hyena", "Jackal", "Wolf", "Fox", 0],
  ["What is the chemical symbol for calcium?", "Cl", "Ca", "Cm", "C", 1],
  ["What is the capital of Zambia?", "Ndola", "Lusaka", "Kitwe", "Livingstone", 1],
  ["Which bird is pink and often stands on one leg?", "Pelican", "Flamingo", "Heron", "Stork", 1],
  ["What is 5 squared?", "10", "20", "25", "35", 2],
  ["What is the capital of Uganda?", "Entebbe", "Kampala", "Jinja", "Gulu", 1],
  ["Which force makes objects fall when dropped?", "Magnetism", "Gravity", "Friction", "Buoyancy", 1],
  ["What is 1000 grams in kilograms?", "0.1", "1", "10", "100", 1],
  ["How many days are in April?", "28", "29", "30", "31", 2],
  ["What is the capital of Cameroon?", "Douala", "Yaoundé", "Garoua", "Bamenda", 1],
  ["What is 2 + 2 × 2?", "6", "8", "4", "10", 0],
  ["Which planet is third from the Sun?", "Venus", "Earth", "Mars", "Mercury", 1],
  ["What do bees help plants do?", "Grow roots", "Pollinate", "Make chlorophyll", "Absorb water", 1],
  ["What is the capital of Rwanda?", "Butare", "Kigali", "Gisenyi", "Ruhengeri", 1],
  ["What is 21 divided by 7?", "2", "3", "4", "5", 1],
  ["How many centimeters are in half a meter?", "25", "50", "75", "100", 1],
  ["What is the capital of Somalia?", "Hargeisa", "Mogadishu", "Kismayo", "Bosaso", 1],
  ["Which planet has liquid water on the surface?", "Mars", "Venus", "Earth", "Titan", 2],
  ["What is 8 squared?", "16", "56", "64", "72", 2],
  ["How many sides does a heptagon have?", "5", "6", "7", "8", 2],
  ["What is the capital of Libya?", "Benghazi", "Tripoli", "Misrata", "Sabha", 1],
  ["Which animal is the largest living bird?", "Eagle", "Emu", "Ostrich", "Albatross", 2],
  ["What is 40% of 50?", "10", "15", "20", "25", 2],
  ["How many hours from noon to midnight?", "6", "10", "12", "24", 2],
  ["What is the capital of Mali?", "Timbuktu", "Bamako", "Gao", "Sikasso", 1],
  ["Which element has atomic number 1?", "Helium", "Hydrogen", "Lithium", "Carbon", 1],
  ["What is 6 × 6?", "30", "36", "42", "48", 1],
  ["What do caterpillars become after metamorphosis?", "Worms", "Butterflies or moths", "Beetles always", "Ants", 1],
  ["What is 27 divided by 3?", "7", "8", "9", "10", 2],
  ["How many days are in December?", "28", "29", "30", "31", 3],
  ["What is the capital of Chad?", "Moundou", "N'Djamena", "Sarh", "Abéché", 1],
  ["Which sense detects temperature on skin?", "Sight", "Touch", "Smell", "Hearing", 1],
  ["What is 17 + 8?", "23", "24", "25", "26", 2],
  ["How many millimeters are in 2 centimeters?", "2", "10", "20", "200", 2],
  ["What is the capital of Burkina Faso?", "Bobo-Dioulasso", "Ouagadougou", "Koudougou", "Banfora", 1],
  ["Which planet has a famous moon named Titan?", "Jupiter", "Saturn", "Neptune", "Uranus", 1],
  ["What is 9 × 9?", "72", "81", "90", "99", 1],
  ["How many sides does a dodecagon have?", "10", "11", "12", "14", 2],
  ["What is the capital of Ghana?", "Kumasi", "Accra", "Tamale", "Cape Coast", 1],
  ["What is 100 − 37?", "53", "63", "73", "67", 1],
  ["Which force opposes motion when surfaces rub?", "Gravity", "Friction", "Magnetism", "Tension", 1],
  ["What is 5 × 12?", "50", "55", "60", "65", 2],
  ["How many days does February have in a leap year?", "28", "29", "30", "31", 1],
  ["What is the capital of Botswana?", "Francistown", "Gaborone", "Maun", "Serowe", 1],
  ["What is 81 divided by 9?", "7", "8", "9", "10", 2],
  ["What is the capital of Sierra Leone?", "Bo", "Freetown", "Kenema", "Makeni", 1],
  ["Which planet is often called Earth's twin in size?", "Mars", "Venus", "Mercury", "Neptune", 1],
  ["What is 7 × 8?", "54", "56", "58", "64", 1],
  ["How many centimeters are in 3 meters?", "30", "300", "3000", "3", 1],
  ["What is the capital of Liberia?", "Gbarnga", "Monrovia", "Buchanan", "Harper", 1],
  ["What is 44 divided by 4?", "9", "10", "11", "12", 2],
  ["How many hours are in 3 days?", "48", "60", "72", "84", 2],
  ["What is the capital of Senegal's neighbor Gambia?", "Brikama", "Banjul", "Bakau", "Farafenni", 1],
  ["Which organ digests food primarily?", "Heart", "Stomach", "Brain", "Lungs", 1],
  ["What is 6 × 7?", "40", "42", "48", "49", 1],
  ["How many months are in half a year?", "4", "5", "6", "7", 2],
  ["What is the capital of Gabon?", "Port-Gentil", "Libreville", "Franceville", "Oyem", 1],
  ["Which animal has eight arms?", "Squid", "Octopus", "Jellyfish", "Crab", 1],
  ["What is 33 + 17?", "40", "50", "55", "60", 1],
  ["What is the capital of Namibia?", "Walvis Bay", "Windhoek", "Swakopmund", "Rundu", 1],
  ["Which animal is known as a ship of the desert?", "Horse", "Camel", "Donkey", "Llama", 1],
  ["What is 14 × 2?", "24", "26", "28", "30", 2],
  ["How many sides does a parallelogram have?", "3", "4", "5", "6", 1],
  ["What is the capital of Mozambique?", "Beira", "Maputo", "Nampula", "Matola", 1],
  ["What is 90 divided by 9?", "8", "9", "10", "11", 2],
  ["How many continents begin with A?", "1", "2", "3", "4", 1],
  ["What is the capital of Madagascar?", "Toamasina", "Antananarivo", "Mahajanga", "Fianarantsoa", 1],
  ["Which animal spins a web?", "Ant", "Spider", "Bee", "Fly", 1],
  ["What is 16 divided by 4?", "2", "3", "4", "5", 2],
  ["How many minutes are in two hours?", "60", "90", "120", "150", 2],
  ["What is the capital of Malawi?", "Blantyre", "Lilongwe", "Mzuzu", "Zomba", 1],
  ["Which gas is needed for fire to burn?", "Nitrogen", "Oxygen", "Carbon dioxide", "Helium", 1],
  ["What is 13 × 3?", "36", "39", "42", "46", 1],
  ["How many days are in a non-leap year?", "364", "365", "366", "367", 1],
  ["What is the capital of South Sudan?", "Malakal", "Juba", "Wau", "Yei", 1],
  ["Which mammal lays eggs?", "Kangaroo", "Platypus", "Koala", "Wombat", 1],
  ["What is 64 divided by 8?", "6", "7", "8", "9", 2],
  ["How many inches are in a foot?", "10", "11", "12", "14", 2],
  ["What is the capital of Lesotho?", "Maseru", "Mafeteng", "Leribe", "Butha-Buthe", 0],
  ["Which sense organ is the nose?", "Sight", "Smell", "Hearing", "Taste", 1],
  ["What is 3 × 15?", "30", "35", "45", "50", 2],
  ["How many days are in June?", "28", "29", "30", "31", 2],
  ["What is 100 divided by 5?", "15", "20", "25", "30", 1],
  ["How many zeros are in one thousand?", "2", "3", "4", "5", 1],
  ["What is the capital of Jamaica?", "Montego Bay", "Kingston", "Spanish Town", "Ocho Rios", 1],
  ["What is the capital of Cuba?", "Santiago", "Havana", "Camagüey", "Varadero", 1],
  ["What is the capital of Panama?", "Colón", "Panama City", "David", "Santiago", 1],
  ["What is the capital of Costa Rica?", "Limón", "San José", "Alajuela", "Heredia", 1],
  ["What is the capital of Qatar?", "Al Wakrah", "Doha", "Al Rayyan", "Lusail", 1],
  ["What is the capital of Kuwait?", "Hawalli", "Kuwait City", "Salmiya", "Jahra", 1],
  ["What is the capital of Bahrain?", "Muharraq", "Manama", "Riffa", "Sitra", 1],
  ["What is the capital of Oman?", "Salalah", "Muscat", "Sohar", "Nizwa", 1],
  ["Which planet has the fastest winds?", "Earth", "Neptune", "Mars", "Venus", 1],
  ["What is 14 divided by 2?", "5", "6", "7", "8", 2],
  ["How many days are in a week?", "5", "6", "7", "8", 2],
  ["What is 25 × 2?", "40", "50", "60", "70", 1],
  ["What is the capital of Fiji?", "Nadi", "Suva", "Lautoka", "Labasa", 1],
  ["Which organ helps filter toxins from blood?", "Heart", "Liver", "Lungs", "Stomach", 1],
  ["What is 6 × 9?", "45", "54", "56", "63", 1],
  ["What is the capital of Bahamas?", "Freeport", "Nassau", "Marsh Harbour", "Alice Town", 1],
  ["Which animal has feathers?", "Bat", "Bird", "Butterfly", "Fish", 1],
  ["What is 48 divided by 6?", "6", "7", "8", "9", 2],
  ["How many seconds are in 5 minutes?", "200", "300", "400", "500", 1],
  ["What is the capital of Barbados?", "Speightstown", "Bridgetown", "Holetown", "Oistins", 1],
  ["What is 15 × 3?", "35", "45", "55", "65", 1],
  ["What is the capital of Haiti?", "Cap-Haïtien", "Port-au-Prince", "Gonaïves", "Les Cayes", 1],
  ["What is 3 × 20?", "40", "50", "60", "70", 2],
  ["What is the capital of Dominican Republic?", "Santiago", "Santo Domingo", "La Romana", "Puerto Plata", 1],
  ["What is 81 divided by 3?", "17", "27", "37", "47", 1],
  ["How many sides does a square have?", "3", "4", "5", "6", 1],
  ["What is 10 × 15?", "100", "150", "200", "250", 1],
  ["How many minutes are in 2.5 hours?", "120", "150", "180", "200", 1],
  ["What is 28 divided by 4?", "5", "6", "7", "8", 2],
  ["What is 6 × 11?", "56", "66", "76", "86", 1],
  ["What is the capital of Nicaragua?", "León", "Managua", "Granada", "Masaya", 1],
  ["What is 42 divided by 6?", "5", "6", "7", "8", 2],
  ["How many centimeters are in 2 meters?", "20", "200", "2000", "2", 1],
  ["What is the capital of Honduras?", "San Pedro Sula", "Tegucigalpa", "La Ceiba", "Choloma", 1],
  ["Which organ helps you hear?", "Nose", "Ear", "Eye", "Tongue", 1],
  ["What is 9 × 4?", "32", "36", "40", "45", 1],
  ["How many hours are in half a day?", "6", "10", "12", "24", 2],
  ["What is the capital of El Salvador?", "Santa Ana", "San Salvador", "San Miguel", "Soyapango", 1],
  ["What is 55 divided by 5?", "9", "10", "11", "12", 2],
  ["What is the capital of Guatemala?", "Antigua", "Guatemala City", "Quetzaltenango", "Escuintla", 1],
  ["What is 7 × 6?", "36", "42", "48", "49", 1],
  ["What is 63 divided by 7?", "7", "8", "9", "10", 2],
  ["How many millimeters are in 3 centimeters?", "3", "30", "300", "3000", 1],
  ["What is 12 × 5?", "50", "60", "70", "80", 1],
  ["How many weeks are in 28 days?", "2", "3", "4", "5", 2],
  ["What is 8 × 5?", "35", "40", "45", "50", 1],
  ["How many minutes are in one hour?", "30", "45", "60", "90", 2],
  ["What is 5 × 5?", "10", "20", "25", "30", 2],
  ["How many days are in July?", "28", "29", "30", "31", 3],
  ["What is 20 × 3?", "40", "50", "60", "70", 2],
  ["How many centimeters are in 5 meters?", "50", "500", "5000", "5", 1],
  ["What is 4 × 25?", "50", "75", "100", "125", 2],
  ["How many minutes are in one day?", "1200", "1440", "1600", "1800", 1],
  ["What is 35 divided by 7?", "4", "5", "6", "7", 1],
  ["What is 8 × 6?", "42", "48", "54", "56", 1],
  ["How many days are in January?", "28", "29", "30", "31", 3],
  ["What is 54 divided by 9?", "5", "6", "7", "8", 1],
  ["How many quarters make 2 wholes?", "4", "6", "8", "10", 2],
  ["What is 2 × 50?", "50", "100", "150", "200", 1],
  ["How many hours are in 4 days?", "72", "84", "96", "100", 2],
  ["What is 16 divided by 2?", "4", "6", "8", "10", 2],
  ["What is 9 × 7?", "56", "63", "72", "81", 1],
  ["How many days are in March?", "28", "29", "30", "31", 3],
  ["What is 60 divided by 5?", "10", "12", "15", "20", 1],
  ["How many meters are in a kilometer?", "10", "100", "1000", "10000", 2],
  ["What is HTML used for?", "Cooking", "Building web pages", "Driving cars", "Growing plants", 1],
  ["How many colors are on most traffic lights?", "2", "3", "4", "5", 1],
  ["What do you call frozen water falling from clouds as flakes?", "Rain", "Snow", "Hail only", "Fog", 1],
  ["Which direction does the sun rise from?", "West", "East", "North", "South", 1],
  ["What is the opposite of hot?", "Warm", "Cold", "Cool only", "Mild", 1],
  ["How many wheels does a typical car have?", "2", "3", "4", "6", 2],
  ["What do you use to write on a blackboard traditionally?", "Pen", "Chalk", "Marker only", "Paint", 1],
  ["Which meal is usually eaten in the morning?", "Dinner", "Breakfast", "Supper", "Brunch only", 1],
  ["What is the plural of mouse (animal)?", "Mouses", "Mice", "Mouse", "Meese", 1],
  ["How many letters are in the word 'quiz'?", "3", "4", "5", "6", 1]
];
